package com.cognizant.training;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ThreeMusketeersApplication {

	public static void main(String[] args) {
		SpringApplication.run(ThreeMusketeersApplication.class, args);
	}

	// Method below will check beans Spring Boot synthesizes on startup, helps with debugging
	/*@Bean
	CommandLineRunner beanCheck(ApplicationContext ctx)
	{
		return args ->
		{
			System.out.println("[DEBUG] Here are the beans generated by Spring Boot:: ");
			String[] beans = ctx.getBeanDefinitionNames();
			Arrays.sort(beans);
			for(String b : beans)
			{
				System.out.println(b);
			}
		};
	}*/
}
